### ISSUE TITLE
Add support for Ruby 3.0

### ISSUE THREAD

**Issue by denzelem** [makandra/modularity#5]
* Add Ruby 3.0 to the test matrix
* Run the gem with Ruby 2.7 and check for deprecation warnings. You might want to check out https://makandracards.com/makandra/496481-changes-to-positional-and-keyword-args-in-ruby-3-0 as help to fixing them.
* Try out the gem in a fresh Rails 6.1 project with Ruby 3.0

**Comment by brunosedler** [comment]
Implemented in https://github.com/makandra/modularity/pull/9 and released in version 3.1
